# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bennett/projects/flow

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bennett/projects/flow

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bennett/projects/flow/CMakeFiles /home/bennett/projects/flow//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bennett/projects/flow/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mp

# Build rule for target.
mp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mp
.PHONY : mp

# fast build rule for target.
mp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/build
.PHONY : mp/fast

#=============================================================================
# Target rules for targets named mpi

# Build rule for target.
mpi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mpi
.PHONY : mpi

# fast build rule for target.
mpi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/build
.PHONY : mpi/fast

#=============================================================================
# Target rules for targets named serial

# Build rule for target.
serial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serial
.PHONY : serial

# fast build rule for target.
serial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/build
.PHONY : serial/fast

#=============================================================================
# Target rules for targets named cuda_sim

# Build rule for target.
cuda_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda_sim
.PHONY : cuda_sim

# fast build rule for target.
cuda_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_sim.dir/build.make CMakeFiles/cuda_sim.dir/build
.PHONY : cuda_sim/fast

cuda.o: cuda.cu.o
.PHONY : cuda.o

# target to build an object file
cuda.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_sim.dir/build.make CMakeFiles/cuda_sim.dir/cuda.cu.o
.PHONY : cuda.cu.o

cuda.i: cuda.cu.i
.PHONY : cuda.i

# target to preprocess a source file
cuda.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_sim.dir/build.make CMakeFiles/cuda_sim.dir/cuda.cu.i
.PHONY : cuda.cu.i

cuda.s: cuda.cu.s
.PHONY : cuda.s

# target to generate assembly for a file
cuda.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda_sim.dir/build.make CMakeFiles/cuda_sim.dir/cuda.cu.s
.PHONY : cuda.cu.s

mp_impl.o: mp_impl.cpp.o
.PHONY : mp_impl.o

# target to build an object file
mp_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/mp_impl.cpp.o
.PHONY : mp_impl.cpp.o

mp_impl.i: mp_impl.cpp.i
.PHONY : mp_impl.i

# target to preprocess a source file
mp_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/mp_impl.cpp.i
.PHONY : mp_impl.cpp.i

mp_impl.s: mp_impl.cpp.s
.PHONY : mp_impl.s

# target to generate assembly for a file
mp_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/mp_impl.cpp.s
.PHONY : mp_impl.cpp.s

mpi_impl.o: mpi_impl.cpp.o
.PHONY : mpi_impl.o

# target to build an object file
mpi_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi_impl.cpp.o
.PHONY : mpi_impl.cpp.o

mpi_impl.i: mpi_impl.cpp.i
.PHONY : mpi_impl.i

# target to preprocess a source file
mpi_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi_impl.cpp.i
.PHONY : mpi_impl.cpp.i

mpi_impl.s: mpi_impl.cpp.s
.PHONY : mpi_impl.s

# target to generate assembly for a file
mpi_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/mpi_impl.cpp.s
.PHONY : mpi_impl.cpp.s

read-geo-data.o: read-geo-data.cpp.o
.PHONY : read-geo-data.o

# target to build an object file
read-geo-data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/read-geo-data.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/read-geo-data.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/read-geo-data.cpp.o
.PHONY : read-geo-data.cpp.o

read-geo-data.i: read-geo-data.cpp.i
.PHONY : read-geo-data.i

# target to preprocess a source file
read-geo-data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/read-geo-data.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/read-geo-data.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/read-geo-data.cpp.i
.PHONY : read-geo-data.cpp.i

read-geo-data.s: read-geo-data.cpp.s
.PHONY : read-geo-data.s

# target to generate assembly for a file
read-geo-data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/read-geo-data.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/read-geo-data.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/read-geo-data.cpp.s
.PHONY : read-geo-data.cpp.s

serial.o: serial.cpp.o
.PHONY : serial.o

# target to build an object file
serial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/serial.cpp.o
.PHONY : serial.cpp.o

serial.i: serial.cpp.i
.PHONY : serial.i

# target to preprocess a source file
serial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/serial.cpp.i
.PHONY : serial.cpp.i

serial.s: serial.cpp.s
.PHONY : serial.s

# target to generate assembly for a file
serial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/serial.cpp.s
.PHONY : serial.cpp.s

write-bmp.o: write-bmp.cpp.o
.PHONY : write-bmp.o

# target to build an object file
write-bmp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/write-bmp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/write-bmp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/write-bmp.cpp.o
.PHONY : write-bmp.cpp.o

write-bmp.i: write-bmp.cpp.i
.PHONY : write-bmp.i

# target to preprocess a source file
write-bmp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/write-bmp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/write-bmp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/write-bmp.cpp.i
.PHONY : write-bmp.cpp.i

write-bmp.s: write-bmp.cpp.s
.PHONY : write-bmp.s

# target to generate assembly for a file
write-bmp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/write-bmp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/write-bmp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/write-bmp.cpp.s
.PHONY : write-bmp.cpp.s

write-jpg.o: write-jpg.cpp.o
.PHONY : write-jpg.o

# target to build an object file
write-jpg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/write-jpg.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/write-jpg.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/write-jpg.cpp.o
.PHONY : write-jpg.cpp.o

write-jpg.i: write-jpg.cpp.i
.PHONY : write-jpg.i

# target to preprocess a source file
write-jpg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/write-jpg.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/write-jpg.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/write-jpg.cpp.i
.PHONY : write-jpg.cpp.i

write-jpg.s: write-jpg.cpp.s
.PHONY : write-jpg.s

# target to generate assembly for a file
write-jpg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mp.dir/build.make CMakeFiles/mp.dir/write-jpg.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mpi.dir/build.make CMakeFiles/mpi.dir/write-jpg.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serial.dir/build.make CMakeFiles/serial.dir/write-jpg.cpp.s
.PHONY : write-jpg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cuda_sim"
	@echo "... mp"
	@echo "... mpi"
	@echo "... serial"
	@echo "... cuda.o"
	@echo "... cuda.i"
	@echo "... cuda.s"
	@echo "... mp_impl.o"
	@echo "... mp_impl.i"
	@echo "... mp_impl.s"
	@echo "... mpi_impl.o"
	@echo "... mpi_impl.i"
	@echo "... mpi_impl.s"
	@echo "... read-geo-data.o"
	@echo "... read-geo-data.i"
	@echo "... read-geo-data.s"
	@echo "... serial.o"
	@echo "... serial.i"
	@echo "... serial.s"
	@echo "... write-bmp.o"
	@echo "... write-bmp.i"
	@echo "... write-bmp.s"
	@echo "... write-jpg.o"
	@echo "... write-jpg.i"
	@echo "... write-jpg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

